global using Godot;
global using System;
global using Soteo.Util.Extensions;
global using Soteo.Shared.Extensions;
global using SysEnvironment = System.Environment;
global using GdEnvironment = Godot.Environment;
global using SysThread = System.Threading.Thread;
global using GdThread = Godot.Thread;
global using GdArray = Godot.Collections.Array;
global using Vector2 = System.Numerics.Vector2;
global using GdVector2 = Godot.Vector2;
global using Object = Godot.Object;